version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - MONGO_USER=mevo
      - MONGO_PASSWORD=mypassword
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mevo
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
